version: 2
executors:
  my-exe:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

jobs:
  build:
    executor: my-exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle install
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  test:
    executor: my-exe
    steps:
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Rspec
          command: bundle exec rspec
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
