version: 2.1
executors:
  my-exe:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    working_directory: ~/myapp
jobs:
  build:
    executor: my-exe
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths: 
            - ~/myapp
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Webpacker install
          command: bundle exec webpacker:install
      - run:
          name: Vue.js Compile
          command: bin/webpack
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  test:
    executor: my-exe
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Rubocop
          command: bundle exec rubocop
      - run:
          name: Rspec
          command: bundle exec rspec
  deploy:
    executor: my-exe
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git catchup:master 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
